CREATE TABLE `prestamos_hist` (
 `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Idenficador único',
 `prestamo_id` int(11) DEFAULT NULL COMMENT 'ID del préstamo al cual corresponde este registro',
 `orden_hist` int(11) DEFAULT NULL COMMENT 'Número de correlatividad de registración',
 `fechahora` datetime DEFAULT NULL COMMENT 'Fecha y hora del registro',
 `fecha_prorroga` datetime DEFAULT NULL COMMENT 'Indica la nueva fecha de vencimiento del préstamo',
 `cobro_id` int(11) DEFAULT NULL COMMENT 'ID del negocio desde el que se emitió el préstamo',
 `ajuste_id` int(11) DEFAULT NULL COMMENT 'ID del ajuste que genero el registro',
 `usuario_id` int(11) DEFAULT NULL COMMENT 'ID del negocio desde el que se emitió el préstamo',
 `porc_iva` decimal(5,2) DEFAULT '0.00' COMMENT 'El porcentaje de IVA',
 `tipo_moneda` varchar(3) CHARACTER SET utf8mb4 DEFAULT 'ARS' COMMENT 'La moneda empleada en los montos',
 `solicitud_id` int(11) DEFAULT NULL COMMENT 'Solicitud que inició el préstamo',
 `entidad` enum('COBRO','MORA','ALTA','BAJA','TRANS','RECALC','PRORROGA','ADELANTO','REVERTIDO','AJUSTE') CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'Qué entidad es la que provoca el registro',
 `estado` enum('SOLIC','PEND','CANC','MORA','REFIN','HOLD','ANUL') CHARACTER SET utf8mb4 DEFAULT 'SOLIC' COMMENT 'Estado actual del préstamo',
 `monto_cobro` decimal(13,4) DEFAULT '0.0000' COMMENT 'El monto del cobro',
 `capital` decimal(13,4) DEFAULT '0.0000' COMMENT 'El capital solicitado',
 `desembolso` decimal(13,4) DEFAULT '0.0000' COMMENT 'Lo realmente desembolsado al cliente.',
 `total_imponible` decimal(13,4) DEFAULT '0.0000' COMMENT 'El total en que se basa el cálculo',
 `total_intereses` decimal(13,4) DEFAULT '0.0000' COMMENT 'Los intereses a cobrar',
 `interes_capital` decimal(13,4) DEFAULT '0.0000' COMMENT 'El interés correspondiente al capital',
 `total_mora` decimal(13,4) DEFAULT '0.0000' COMMENT 'El monto del punitorio por mora',
 `total_cargos` decimal(13,4) DEFAULT '0.0000' COMMENT 'La suma de todos los cargos a cobrar',
 `cargos_administrativos` decimal(13,4) DEFAULT '0.0000' COMMENT 'El monto de los cargos administrativos',
 `cargos_cobranza` decimal(13,4) DEFAULT '0.0000' COMMENT 'El monto de los cargos por cobranza',
 `total_impuestos` decimal(13,4) DEFAULT '0.0000' COMMENT 'La suma de todos los impuestos a cobrar',
 `total_iva` decimal(13,4) DEFAULT '0.0000' COMMENT 'La suma del impuesto IVA',
 `total_iva_interes` decimal(13,4) DEFAULT '0.0000' COMMENT 'El monto del IVA del interés a cobrar',
 `iva_interes_capital` decimal(13,4) DEFAULT '0.0000' COMMENT 'El IVA del interés cobrado sobre el capital',
 `iva_mora` decimal(13,4) DEFAULT '0.0000' COMMENT 'El IVA cobrado por la mora o punitorio',
 `total_iva_cargos` decimal(13,4) DEFAULT '0.0000' COMMENT 'La suma del IVA por cargos extras',
 `iva_cargos_administrativos` decimal(13,4) DEFAULT '0.0000' COMMENT 'IVA de los cargos administrativos',
 `iva_cargos_cobranza` decimal(13,4) DEFAULT '0.0000' COMMENT 'IVA por cargos por cobranza',
 `total_impuestos_1` decimal(13,4) DEFAULT '0.0000' COMMENT 'Total impuesto para uso futuro',
 `total_impuestos_2` decimal(13,4) DEFAULT '0.0000' COMMENT 'Total impuesto para uso futuro',
 `total_facturado` decimal(13,4) DEFAULT '0.0000' COMMENT 'Monto acumulado de lo que se lleva facturado.',
 `total_pagado` decimal(13,4) DEFAULT '0.0000' COMMENT 'Monto acumulado de lo que cl cliente lleva pagado sobre este préstamo.',
 `tasas` json DEFAULT NULL COMMENT 'Las tasas resultantes de los cálculos',
 `tasas_impuestos` json DEFAULT NULL COMMENT 'Las tasas impositivas usadas.',
 `tasas_cargos` json DEFAULT NULL COMMENT 'Las tasas de los cargos aplicados',
 `observaciones` text CHARACTER SET utf8mb4 COMMENT 'Cualquier nota textual que se necesite agregar',
 PRIMARY KEY (`id`),
 KEY `fechahora` (`fechahora`),
 KEY `orden_hist` (`orden_hist`),
 KEY `cobro_id` (`cobro_id`),
 KEY `prestamo_id` (`prestamo_id`),
 KEY `prestamo_orden` (`prestamo_id`,`orden_hist`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Esto es el historial de actualización de los préstamos 2.0'