CREATE TABLE `cuotas_hist` (
 `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Identificador único',
 `prestamo_id` int(11) DEFAULT NULL COMMENT 'ID del préstamo al que pertenece la cuota',
 `cuota_id` int(11) DEFAULT NULL COMMENT 'ID de la cuota de referencia',
 `orden` int(11) NOT NULL DEFAULT '1' COMMENT 'Indica el orden del historial',
 `monto_cuota` decimal(16,4) DEFAULT NULL COMMENT 'Monto calculado a pagar de la cuota',
 `tipo_moneda` varchar(4) DEFAULT 'MXN' COMMENT 'La moneda con la que se debe interpretar los montos',
 `estado` enum('PEND','CANC','MORA','REFIN','HOLD','PAGP','DIFCAP','PROR','PAGCAP','PAGINT') CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT 'PEND' COMMENT 'Estado de habilitación',
 `estado_ant` enum('SOLIC','PEND','CANC','MORA','REFIN','HOLD','PAGP','DIFCAP','PROR','PAGCAP','PAGINT') CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT 'Estado anterior del préstamo',
 `fecha_venc` date DEFAULT NULL COMMENT 'Fecha de vencimiento de la cuota',
 `dias` int(11) DEFAULT NULL COMMENT 'Dias transcurridos con la cuota anterior',
 `interes_cuota` decimal(16,4) DEFAULT NULL COMMENT 'Monto interés cobrado en esta cuota',
 `iva_interes_cuota` decimal(16,4) DEFAULT NULL COMMENT 'El IVA sobre el interés cobrado en la cuota',
 `capital` decimal(16,4) DEFAULT NULL COMMENT 'Monto_cuota menos interes_cuota',
 `fecha_cobro` datetime DEFAULT NULL COMMENT 'fecha de cobro de la cuota',
 `cobro_id` int(11) DEFAULT NULL COMMENT 'ID del comprobante de cobro',
 `monto_mora` decimal(16,4) DEFAULT NULL COMMENT 'Monto del sobrecargo por mora ',
 `total_iva_mora` decimal(16,4) DEFAULT NULL COMMENT 'El IVA que se cobra sobre el monto de la mora ',
 `saldo_inicio_periodo` decimal(16,4) DEFAULT NULL COMMENT 'Saldo al inicio de la cuota ',
 `saldo_final_periodo` decimal(16,4) DEFAULT NULL COMMENT 'Saldo al final de la cuota',
 `va_a_mora` enum('SI','NO') CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT 'SI' COMMENT 'Indica si la cuota actual va a mora o se traspasa su fecha de vencimiento',
 `operacion` varchar(255) DEFAULT NULL,
 `sys_fecha_alta` datetime DEFAULT NULL,
 `sys_fecha_modif` datetime DEFAULT NULL,
 `sys_usuario_id` int(11) DEFAULT NULL,
 PRIMARY KEY (`id`),
 KEY `prestamo_id` (`prestamo_id`),
 KEY `estado` (`estado`,`fecha_venc`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Historial de Cuotas de los préstamos'