CREATE TABLE `prestamos` (
 `id` int(11) NOT NULL AUTO_INCREMENT COMMENT ' Idenficador unico',
 `persona_id` int(11) DEFAULT NULL COMMENT 'ID de la persona titular del préstamo',
 `tenant` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'El tenant al cual pertenece este préstamo',
 `negocio_id` int(11) DEFAULT NULL COMMENT 'ID del negocio desde el que se emitió el préstamo',
 `plan_id` int(11) DEFAULT NULL COMMENT 'ID del plan usado en el prestamo',
 `pais_origen` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT 'ARG' COMMENT 'País para el cual se originó el préstamo',
 `estado` enum('SOLIC','PEND','CANC','MORA','REFIN','HOLD','ANUL','HDAL') CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT 'SOLIC' COMMENT 'Estado actual del préstamo',
 `estado_ant` enum('SOLIC','PEND','CANC','MORA','REFIN','HOLD','ANUL','HDAL') CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'Estado anterior del préstamo',
 `fechahora_emision` datetime DEFAULT NULL COMMENT 'Fecha y hora (relativa al país) de emisión del préstamo',
 `fecha_vencimiento` datetime DEFAULT NULL COMMENT 'Fecha de vencimiento del préstamo',
 `fecha_vencimiento_anterior` datetime DEFAULT NULL COMMENT 'Fecha de vencimiento anterior del préstamo',
 `tipo_moneda` varchar(3) DEFAULT 'ARS',
 `calculo` varchar(32) DEFAULT NULL COMMENT 'Algoritmo de cálculo usado en el préstamo',
 `periodo` int(11) DEFAULT '0' COMMENT 'Período usado en el préstamo',
 `capital` decimal(13,4) DEFAULT '0.0000' COMMENT 'El capital solicitado',
 `total_imponible` decimal(13,4) DEFAULT '0.0000' COMMENT 'El total en que se basa el cálculo',
 `total_intereses` decimal(13,4) DEFAULT '0.0000' COMMENT 'Los intereses a cobrar',
 `interes_capital` decimal(13,4) DEFAULT '0.0000' COMMENT 'El interés correspondiente al capital',
 `total_mora` decimal(13,4) DEFAULT '0.0000' COMMENT 'El monto del punitorio por mora',
 `total_cargos` decimal(13,4) DEFAULT '0.0000' COMMENT 'La suma de todos los cargos a cobrar',
 `cargos_administrativos` decimal(13,4) DEFAULT '0.0000' COMMENT 'El monto de los cargos administrativos',
 `cargos_cobranza` decimal(13,4) DEFAULT '0.0000' COMMENT 'El monto de los cargos por cobranza',
 `total_impuestos` decimal(13,4) DEFAULT '0.0000' COMMENT 'La suma de todos los impuestos a cobrar',
 `total_iva` decimal(13,4) DEFAULT '0.0000' COMMENT 'La suma del impuesto IVA',
 `total_iva_interes` decimal(13,4) DEFAULT '0.0000' COMMENT 'El monto del IVA del interés a cobrar',
 `iva_interes_capital` decimal(13,4) DEFAULT '0.0000' COMMENT 'El IVA del interés cobrado sobre el capital',
 `iva_mora` decimal(13,4) DEFAULT '0.0000' COMMENT 'El IVA cobrado por la mora o punitorio',
 `total_iva_cargos` decimal(13,4) DEFAULT '0.0000' COMMENT 'La suma del IVA por cargos extras',
 `iva_cargos_administrativos` decimal(13,4) DEFAULT '0.0000' COMMENT 'IVA de los cargos administrativos',
 `iva_cargos_cobranza` decimal(13,4) DEFAULT '0.0000' COMMENT 'IVA por cargos por cobranza',
 `total_impuestos_1` decimal(13,4) DEFAULT '0.0000' COMMENT 'Total impuesto para uso futuro',
 `total_impuestos_2` decimal(13,4) DEFAULT '0.0000' COMMENT 'Total impuesto para uso futuro',
 `total_facturado` decimal(13,4) DEFAULT '0.0000' COMMENT 'Monto acumulado de lo que se lleva facturado.',
 `total_pagado` decimal(13,4) DEFAULT '0.0000' COMMENT 'Monto acumulado de lo que cl cliente lleva pagado sobre este préstamo.',
 `tasas` json DEFAULT NULL COMMENT 'Las tasas resultantes de los cálculos',
 `tasas_impuestos` json DEFAULT NULL COMMENT 'Las tasas impositivas usadas.',
 `tasas_cargos` json DEFAULT NULL COMMENT 'Las tasas de los cargos aplicados',
 `data` json DEFAULT NULL COMMENT 'Cualquier otro dato',
 `data_transferencia` json DEFAULT NULL COMMENT 'Datos resultantes de la transferencia',
 `data_refinanciacion` json DEFAULT NULL COMMENT 'IDs cruzados entre el préstamo que refinancia éste o el préstamo que es refinanciación de éste.',
 `facturado` tinyint(4) DEFAULT '0' COMMENT 'Bandera de facturado',
 `solicitud_id` int(11) DEFAULT NULL COMMENT 'ID de la solicitud que generó este préstamo',
 `orden` int(11) DEFAULT '1' COMMENT 'Orden en el que aparece para el cliente.',
 `linea_credito_id` int(11) DEFAULT NULL COMMENT 'Línea de crédito contable para este préstamo',
 `calcular_mora` tinyint(1) DEFAULT '1' COMMENT 'Indica si calcular la mora o no',
 `sys_fecha_alta` datetime DEFAULT NULL COMMENT 'Fecha y hora de creación del registro',
 `sys_fecha_modif` datetime DEFAULT NULL COMMENT 'Fecha y hora de modioficación del registro',
 `sys_usuario_id` int(11) DEFAULT NULL COMMENT 'Usuario que modificó el registro',
 PRIMARY KEY (`id`),
 KEY `persona_id` (`persona_id`),
 KEY `negocio_id` (`negocio_id`),
 KEY `plan_id` (`plan_id`),
 KEY `tenant` (`tenant`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Almacena los préstamos versión 2.0'