<?php
/*
	Listado de errores explicados.
*/
const WS_INTERNAL_ERRORS = array(
	0=>'No hay errores',
	1=>'Versión de PHP no válida, tiene que ser 5.4 o superior.',
	2=>'La biblioteca cURL no está incluida, no se puede continuar.',
	3=>'Se necesita una conexión con la base de datos para continuar.'
);

const WS_INTERNAL_CODES = array(
	0=>'Success.',
	// Errores del usuario del ws.
	1=>'Se requiere login',
	2=>'Nombre de usuario o contraseña requerido',
	3=>'Login incorrecto',
	4=>'Token no recibido',
	5=>'Token no es válido',
	6=>'Token ha expirado',
	// Errores de los datos.
	10=>'Falta parámetro requerido',
	11=>'Hay datos erróneos en la petición',
	12=>'Cuerpo de mensaje no válido',
	13=>'Objeto buscado no fue encontrado',
	14=>'Parámetro faltante',
	15=>'ID de usuario requerido',
	// Excepciones en los datos.
	20=>'No permitido',
	21=>'Negocio del usuario y el objeto no coinciden',
	// Errores en la petición HTTP
	40=>'API no encontrada',
	41=>'Método no aceptado',
	42=>'Servicio no existe o parámetro incorrecto',
	// Errores de CBU/Cuenta de banco.
	50=>'Formato incorrecto de CBU',
	51=>'CBU no es válido',
	52=>'Cuenta inactiva',
	53=>'Tipo de cuenta no permitida',
	54=>'Código de banco inexistente',
	// Errores internos.
	// Blacklist
	60=>'La persona está omitida',
	// Errores de pin
	65=>'La solicitud no tiene número de teléfono',
	66=>'Teléfono ya ha sido validado',
	67=>'PIN no válido',
	68=>'Número de teléfono en formato incorrecto',
	69=>'La solicitud no tiene PinID',
	// Emails.
	70=>'La solicitud no tiene dirección de correo electrónico',
	71=>'La dirección de correo electrónico ya fue verificada',
	72=>'Dirección de correo electrónico no válida',
	73=>'Formato de dirección de correo electrónico no válido',
	74=>'No hay servicio de envío de correo electrónico',
	80=>'Código de aceptación no indicado',
	81=>'Solicitud no tiene Código de aceptación',
	82=>'Código de aceptación no válido',
	// Errores de cifrado.
	101=>'Falta archivo de configuración de la API',
	102=>'Resolver no encontrado.',
	103=>'Algoritmo de cifrado no soportado',
	104=>'No se esperaba cifrado',
	105=>'El cifrado del mensaje es incorrecto',
	106=>'Error interno',
	// Errores de los usuarios del front.
	120=>'Nombre de usuario o contraseña incorrecta',
	121=>'Usuario no encontrado',
	130=>'No se pudo procesar archivo PDF',
	//Errores al al momento de crear, editar o aprobar una solicitud
	140=>'No se pudo crear la solicitud',
	141=>'No se pudo modificar la solicitud',
	142=>'No se pudo aprobar la solicitud',
	143=>'El Documento indicado no es válido',
	144=>'La contraseña no cumple el criterio de seguridad',
	145=>'Debes indicar el plazo',
	146=>'Debes indicar el capital',
	147=>'Debes indicar el plan a utilizar',
	148=>'Los datos aportados no cumplen los requisitos',
	149=>'No se indicaron datos para modificar',
	150=>'Solicitud ya procesada',
	151=>'No se pudo crear la persona para esta solicitud',
	152=>'Datos no aceptables',
	153=>'Solicitud no encontrada',
	//Personas
	160=>'La persona indicada no fue encontrada',
	161=>'Datos de la persona no encontrados',
	//Configs/parametros
	170=>"El parámetro a editar no fue encontrado",
	171=>'No se pudo editar el parámetro',
	172=>'Grupo indicadó no encontrado',
	173=>"Estado indicadó no válido",
	//Prestamos
	180=>'Debes indicar el ID del préstamo',
	181=>'Préstamo no encontrado',
	//Biblioteca
	190=>'Biblioteca no encontrada',
	191=>'Biblioteca sin directorio físico',
	192=>'Archivo no encontrado',
	193=>'Archivo no disponible de manera física',
	194=>'No se pudo leer el archivo indicadó',
	195=>'Debes indicar la carpeta a crear',
	196=>'El nombre de la carpeta a crear no es válido',
	197=>'No se pudo crear la carpeta indicada',
	198=>'La carpeta destino no existe',
	199=>'No se pudo realizar la subida del archivo',
	200=>'Debes indicar el nombre del archivo a subir',
	201=>'Los datos del archivo a subir no pueden estar vacíos',
	//Marcas
	210=>'Debes indicar el nombre de la marca',
	211=>'No se pudo crear la marca',
	212=>'Debes indicar el identificador de la marca',
	213=>'Debes indicar datos para modificar la marca',
	214=>'No se pudo editar la marca',
	215=>'Marca no encontrada',
	216=>'El nombre de la marca ya existe',
	//Modelos
	220=>'Debes indicar el nombre del modelo',
	221=>'Debes indicar la marca del modelo',
	222=>'No se pudo crear el modelo',
	223=>'Debes indicar el identificador del modelo',
	224=>'Debes indicar datos para modificar el modelo',
	225=>'No se pudo editar el modelo',
	226=>'Modelo no encontrado',
	227=>"Características disponibles no encontradas",
	//Productos
	230=>'Debes indicar el nombre del producto',
	231=>'Debes indicar el modelo del producto',
	232=>'Debes indicar el precio del producto',
	233=>'No se pudo crear el producto',
	234=>'Debes indicar el identificador del producto',
	235=>'Debes indicar datos para modificar del producto',
	236=>'No se pudo editar el producto',
	237=>'Producto no encontrado',
	//Archivos en general
	240=>'Tipo de imagen no admitido',
	241=>'No se pudo guardar la imagen'
);

const CURL_ERRORS = array(
		0=>'CURLE_OK: No hay errores',
		 1=> 'CURLE_UNSUPPORTED_PROTOCOL: cURL no soporta el protocolo usado.', 
		 2=> 'CURLE_FAILED_INIT: Error interno, cURL no se pudo inicializar.', 
		 3=> 'CURLE_URL_MALFORMAT: La URL no está formada apropiadamente.', 
		 4=> 'CURLE_NOT_BUILT_IN: La característica, protocolo u opción solicitada no está disponible.', 
		 5=> 'CURLE_COULDNT_RESOLVE_PROXY: El host proxy no pude ser resuelto.', 
		 6=> 'CURLE_COULDNT_RESOLVE_HOST: El host remoto no pudo ser resuelto.', 
		 7=> 'CURLE_COULDNT_CONNECT: No se pudo conectar al host o proxy.', 
		 8=> 'CURLE_FTP_WEIRD_SERVER_REPLY: Los datos enviados por el servidor no se pudieron interpretar.',
		 9=> 'CURLE_REMOTE_ACCESS_DENIED: El servidor denegó el acceso.',
		 10=> 'CURLE_FTP_ACCEPT_FAILED: El servidor regresó un error mientras se espera por la reconexión en la sesión actual.',
		 11=> 'CURLE_FTP_WEIRD_PASS_REPLY: Respuesta del servidor no reconocida al enviarle la contraseña.',
		 12=> 'CURLE_FTP_ACCEPT_TIMEOUT: Tiempo de espera agotado mientras se esperaba a conectar con el servidor.',
		 13=> 'CURLE_FTP_WEIRD_PASV_REPLY: El servidor no regresó una respuesta comprensible a PASV o EPSV.',
		 14=> 'CURLE_FTP_WEIRD_227_FORMAT: El servidor regresó una línea 227- incomprensible como respuesta a PASV.',
		 15=> 'CURLE_FTP_CANT_GET_HOST: Error interno al tratar de resolver el host usado en la nueva conexión.',
		 17=> 'CURLE_FTP_COULDNT_SET_TYPE: ',
		 18=> 'CURLE_PARTIAL_FILE',
		 19=> 'CURLE_FTP_COULDNT_RETR_FILE',
		 21=> 'CURLE_QUOTE_ERROR',
		 22=> 'CURLE_HTTP_RETURNED_ERROR: El servidor respondió con un error de HTTP.',
		 23=> 'CURLE_WRITE_ERROR',
		 25=> 'CURLE_UPLOAD_FAILED',
		 26=> 'CURLE_READ_ERROR',
		 27=> 'CURLE_OUT_OF_MEMORY: Memoria interna agotada.',
		 28=> 'CURLE_OPERATION_TIMEDOUT: Tiempo de espera agotado para la operación actual.',
		 30=> 'CURLE_FTP_PORT_FAILED',
		 31=> 'CURLE_FTP_COULDNT_USE_REST',
		 33=> 'CURLE_RANGE_ERROR: El servidor no acepta o no soporta requerimientos de rangos.',
		 34=> 'CURLE_HTTP_POST_ERROR: Error desconocido, confusión interna de cURL.',
		 35=> 'CURLE_SSL_CONNECT_ERROR: Problema encontrado mientras se hacía handshake de SSL/TLS',
		 36=> 'CURLE_BAD_DOWNLOAD_RESUME',
		 37=> 'CURLE_FILE_COULDNT_READ_FILE',
		 38=> 'CURLE_LDAP_CANNOT_BIND',
		 39=> 'CURLE_LDAP_SEARCH_FAILED',
		 41=> 'CURLE_FUNCTION_NOT_FOUND',
		 42=> 'CURLE_ABORTED_BY_CALLBACK',
		 43=> 'CURLE_BAD_FUNCTION_ARGUMENT',
		 45=> 'CURLE_INTERFACE_FAILED',
		 47=> 'CURLE_TOO_MANY_REDIRECTS: Demasiadas redirecciones.',
		 48=> 'CURLE_UNKNOWN_TELNET_OPTION',
		 49=> 'CURLE_TELNET_OPTION_SYNTAX',
		 51=> 'CURLE_PEER_FAILED_VERIFICATION',
		 52=> 'CURLE_GOT_NOTHING: El servidor devolvió una respuesta vacía.',
		 53=> 'CURLE_SSL_ENGINE_NOTFOUND: El motor SSL especificado no fue encontrado.',
		 54=> 'CURLE_SSL_ENGINE_SETFAILED: Se falló al establecer el motor SSL especificado.',
		 55=> 'CURLE_SEND_ERROR: No se pudo enviar datos por la red.',
		 56=> 'CURLE_RECV_ERROR: Fallo al recibir datos de la red.',
		 58=> 'CURLE_SSL_CERTPROBLEM',
		 59=> 'CURLE_SSL_CIPHER',
		 60=> 'CURLE_SSL_CACERT',
		 61=> 'CURLE_BAD_CONTENT_ENCODING: Codificación de transferencia no reconocida.',
		 62=> 'CURLE_LDAP_INVALID_URL',
		 63=> 'CURLE_FILESIZE_EXCEEDED: Tamaño de archivo demasiado grande.',
		 64=> 'CURLE_USE_SSL_FAILED',
		 65=> 'CURLE_SEND_FAIL_REWIND',
		 66=> 'CURLE_SSL_ENGINE_INITFAILED',
		 67=> 'CURLE_LOGIN_DENIED: El servidor denegó la entrada.',
		 68=> 'CURLE_TFTP_NOTFOUND',
		 69=> 'CURLE_TFTP_PERM',
		 70=> 'CURLE_REMOTE_DISK_FULL',
		 71=> 'CURLE_TFTP_ILLEGAL',
		 72=> 'CURLE_TFTP_UNKNOWNID',
		 73=> 'CURLE_REMOTE_FILE_EXISTS',
		 74=> 'CURLE_TFTP_NOSUCHUSER',
		 75=> 'CURLE_CONV_FAILED',
		 76=> 'CURLE_CONV_REQD',
		 77=> 'CURLE_SSL_CACERT_BADFILE',
		 78=> 'CURLE_REMOTE_FILE_NOT_FOUND: Archivo remoto no encontrado.',
		 79=> 'CURLE_SSH',
		 80=> 'CURLE_SSL_SHUTDOWN_FAILED',
		 81=> 'CURLE_AGAIN',
		 82=> 'CURLE_SSL_CRL_BADFILE',
		 83=> 'CURLE_SSL_ISSUER_ERROR',
		 84=> 'CURLE_FTP_PRET_FAILED',
		 84=> 'CURLE_FTP_PRET_FAILED',
		 85=> 'CURLE_RTSP_CSEQ_ERROR',
		 86=> 'CURLE_RTSP_SESSION_ERROR',
		 87=> 'CURLE_FTP_BAD_FILE_LIST',
		 88=> 'CURLE_CHUNK_FAILED'
	);

const HTTP_CODES = array(
		200=>'Recurso encontrado',
		201=>'Recurso creado',
		202=>'Petición aceptada',
		203=>'Información no autoritativa',
		204=>'Sin contenido',
		205=>'Recargar contenido',
		206=>'Contenido parcial',
		207=>'Estado múltiple',
		
		300=>'Múltiples opciones',
		301=>'Movido permanentemente',
		302=>'Movido temporalmente',
		303=>'Vea otra',
		304=>'No modificado',
		305=>'Utilice un proxy',
		306=>'Cambie de proxy',
		307=>'Redirección temporal',

		400=>'Solicitud incorrecta',
		401=>'No autorizado',
		402=>'Pago requerido',
		403=>'Prohibido',
		404=>'No encontrado',
		405=>'Método no permitido',
		406=>'No aceptable',
		407=>'Autenticación Proxy requerida',
		408=>'Tiempo de espera agotado',
		409=>'Conflicto',
		410=>'Ya no disponible',
		411=>'Requiere longitud',
		412=>'Falló precondición',
		413=>'Solicitud demasiado larga',
		414=>'URI demasiado larga',
		415=>'Tipo de medio no soportado',
		416=>'Rango solicitado no disponible',
		417=>'Falló expectativa',
		421=>'Hay muchas conexiones desde esta dirección de internet',
		422=>'Entidad no procesable (WebDAV - RFC 4918)',
		423=>'Bloqueado (WebDAV - RFC 4918)',
		424=>'Falló dependencia (WebDAV) (RFC 4918)',
		425=>'Colección sin ordenar',
		426=>'Actualización requerida (RFC 2817)',
		449=>'Reintente con',

		500=>'Error interno',
		501=>'No implementado',
		502=>'Pasarela incorrecta',
		503=>'Servicio no disponible',
		504=>'Tiempo de espera de la pasarela agotado',
		505=>'Versión de HTTP no soportada',
		506=>'Variante también negocia (RFC 2295)',
		507=>'Almacenamiento insuficiente (WebDAV - RFC 4918)',
		509=>'Límite de ancho de banda excedido',
		510=>'No extendido (RFC 2774)'
	);
const JSON_ERRORS = array(
				 JSON_ERROR_DEPTH => 'Se excedió la profundidad máxima de la pila.',
		JSON_ERROR_STATE_MISMATCH => 'Subdesbordamiento o el modo no coincide.',
			 JSON_ERROR_CTRL_CHAR => 'Se encontró un caracter de control inesperado.',
				JSON_ERROR_SYNTAX => 'Error de sintaxis. JSON mal formado.',
				  JSON_ERROR_UTF8 => 'Caracter UTF-8 mal formado, posiblemente mal codificado.',
			 JSON_ERROR_RECURSION => 'Una o más referencias recursivas en el valor a codificar',
			JSON_ERROR_INF_OR_NAN => 'Uno o más valores NAN o INF en el valor a codificar',
	  JSON_ERROR_UNSUPPORTED_TYPE => 'Se proporcionó un valor de un tipo que no se puede codificar',
 JSON_ERROR_INVALID_PROPERTY_NAME => 'Se dio un nombre de una propiedad que no puede ser codificada',
				 JSON_ERROR_UTF16 => 'Caracteres UTF-16 malformados, posiblemente codificados de forma incorrecta'
);
	
	

const SITIOS = array("ALL","MIC");
const PEOPLEMSG = array("P","U","E");