DROP TABLE IF EXISTS `permisos_roles`;
CREATE TABLE IF NOT EXISTS `permisos_roles` (
  `id` int NOT NULL AUTO_INCREMENT,
  `nombre` varchar(80) DEFAULT NULL,
  `plantilla` json DEFAULT NULL,
  `estado` enum('HAB','DES','ELI') NOT NULL DEFAULT 'HAB',
  `sys_fecha_alta` datetime DEFAULT NULL,
  `sys_fecha_modif` datetime DEFAULT NULL,
  `sys_usuario_id` int DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Volcado de datos para la tabla `permisos_roles`
--

INSERT INTO `permisos_roles` (`id`, `nombre`, `plantilla`, `estado`, `sys_fecha_alta`, `sys_fecha_modif`, `sys_usuario_id`) VALUES
(1, 'Vendedor', '[{\"id\": \"2\", \"alias\": \"inicio\", \"nombre\": \"Dashboard\", \"permisos\": [\"r\", \"c\", \"u\", \"d\"]}, {\"id\": \"20\", \"alias\": \"solicitudes\", \"childs\": [{\"id\": \"21\", \"alias\": \"listado\", \"nombre\": \"Listado de solicitudes\", \"permisos\": [\"r\", \"c\"]}], \"nombre\": \"Solicitudes\", \"permisos\": [\"r\", \"c\", \"u\", \"d\"]}, {\"id\": \"25\", \"alias\": \"planes\", \"childs\": [{\"id\": \"26\", \"alias\": \"listado\", \"nombre\": \"Lista Planes\"}, {\"id\": \"27\", \"alias\": \"formulario-plan\", \"nombre\": \"Formulario plan\"}], \"nombre\": \"Planes\", \"permisos\": [\"r\", \"c\", \"u\", \"d\"]}, {\"id\": \"30\", \"alias\": \"usuarios\", \"childs\": [{\"id\": \"31\", \"alias\": \"listado\", \"nombre\": \"Lista usuarios\"}], \"nombre\": \"Usuarios\", \"permisos\": [\"r\", \"c\", \"u\", \"d\"]}, {\"id\": \"90\", \"alias\": \"tests\", \"childs\": [{\"id\": \"91\", \"alias\": \"testmodalbs5\", \"nombre\": \"Modal para Bootstrap 5\", \"permisos\": [\"r\", \"c\", \"u\", \"d\"]}], \"nombre\": \"Test varios\"}, {\"id\": \"100\", \"alias\": \"configuracion\", \"childs\": [{\"id\": \"102\", \"alias\": \"parametros\", \"nombre\": \"Parámetros\"}], \"nombre\": \"Configuración\", \"permisos\": [\"r\", \"c\", \"u\", \"d\"]}, {\"id\": \"103\", \"alias\": \"permisos\", \"childs\": [{\"id\": \"104\", \"alias\": \"editar\", \"nombre\": \"Editar permisos\", \"permisos\": [\"r\", \"c\", \"u\", \"d\"]}], \"nombre\": \"Permisos\", \"permisos\": [\"r\"]}]', 'HAB', NULL, '2021-10-29 16:42:56', 1),
(7, 'Otro Rol', '[{\"id\": \"2\", \"alias\": \"inicio\", \"nombre\": \"Dashboard\", \"permisos\": [\"r\", \"c\", \"u\", \"d\"]}, {\"id\": \"20\", \"alias\": \"solicitudes\", \"childs\": [{\"id\": \"21\", \"alias\": \"listado\", \"nombre\": \"Listado de solicitudes\", \"permisos\": [\"r\", \"c\"]}], \"nombre\": \"Solicitudes\", \"permisos\": [\"r\", \"c\", \"u\", \"d\"]}, {\"id\": \"25\", \"alias\": \"planes\", \"childs\": [{\"id\": \"26\", \"alias\": \"listado\", \"nombre\": \"Lista Planes\"}, {\"id\": \"27\", \"alias\": \"formulario-plan\", \"nombre\": \"Formulario plan\"}], \"nombre\": \"Planes\", \"permisos\": [\"r\", \"c\", \"u\", \"d\"]}, {\"id\": \"30\", \"alias\": \"usuarios\", \"childs\": [{\"id\": \"31\", \"alias\": \"listado\", \"nombre\": \"Lista usuarios\"}], \"nombre\": \"Usuarios\", \"permisos\": [\"r\", \"c\", \"u\", \"d\"]}, {\"id\": \"90\", \"alias\": \"tests\", \"childs\": [{\"id\": \"91\", \"alias\": \"testmodalbs5\", \"nombre\": \"Modal para Bootstrap 5\", \"permisos\": [\"r\", \"c\", \"u\", \"d\"]}], \"nombre\": \"Test varios\"}, {\"id\": \"100\", \"alias\": \"configuracion\", \"childs\": [{\"id\": \"102\", \"alias\": \"parametros\", \"nombre\": \"Parámetros\"}], \"nombre\": \"Configuración\", \"permisos\": [\"r\", \"c\", \"u\", \"d\"]}, {\"id\": \"103\", \"alias\": \"permisos\", \"childs\": [{\"id\": \"104\", \"alias\": \"editar\", \"nombre\": \"Editar permisos\", \"permisos\": [\"r\", \"c\", \"u\", \"d\"]}], \"nombre\": \"Permisos\", \"permisos\": [\"r\"]}]', 'HAB', '2021-11-01 09:07:43', '2021-11-01 09:10:29', 1),
(6, 'Negociante', '[{\"id\": \"2\", \"alias\": \"inicio\", \"nombre\": \"Dashboard\", \"permisos\": [\"r\", \"c\", \"u\", \"d\"]}, {\"id\": \"20\", \"alias\": \"solicitudes\", \"childs\": [{\"id\": \"21\", \"alias\": \"listado\", \"nombre\": \"Listado de solicitudes\", \"permisos\": [\"r\", \"c\"]}], \"nombre\": \"Solicitudes\", \"permisos\": [\"r\", \"c\", \"u\", \"d\"]}, {\"id\": \"25\", \"alias\": \"planes\", \"childs\": [{\"id\": \"26\", \"alias\": \"listado\", \"nombre\": \"Lista Planes\"}, {\"id\": \"27\", \"alias\": \"formulario-plan\", \"nombre\": \"Formulario plan\"}], \"nombre\": \"Planes\", \"permisos\": [\"r\", \"c\", \"u\", \"d\"]}, {\"id\": \"30\", \"alias\": \"usuarios\", \"childs\": [{\"id\": \"31\", \"alias\": \"listado\", \"nombre\": \"Lista usuarios\"}], \"nombre\": \"Usuarios\", \"permisos\": [\"r\", \"c\", \"u\", \"d\"]}, {\"id\": \"90\", \"alias\": \"tests\", \"childs\": [{\"id\": \"91\", \"alias\": \"testmodalbs5\", \"nombre\": \"Modal para Bootstrap 5\", \"permisos\": [\"r\", \"c\", \"u\", \"d\"]}], \"nombre\": \"Test varios\"}, {\"id\": \"100\", \"alias\": \"configuracion\", \"childs\": [{\"id\": \"102\", \"alias\": \"parametros\", \"nombre\": \"Parámetros\"}], \"nombre\": \"Configuración\", \"permisos\": [\"r\", \"c\", \"u\", \"d\"]}, {\"id\": \"103\", \"alias\": \"permisos\", \"childs\": [{\"id\": \"104\", \"alias\": \"editar\", \"nombre\": \"Editar permisos\", \"permisos\": [\"r\", \"c\", \"u\", \"d\"]}], \"nombre\": \"Permisos\", \"permisos\": [\"r\"]}]', 'HAB', '2021-11-01 08:59:39', '2021-11-01 08:59:39', 1);