CREATE TABLE IF NOT EXISTS `personas` (
  `id` int NOT NULL AUTO_INCREMENT,
  `solicitud_id` int DEFAULT NULL COMMENT 'ID que se arrastra de cuando la persona era un solicitante',
  `nombre` varchar(100) DEFAULT NULL,
  `apellido` varchar(100) DEFAULT NULL,
  `tipo_doc` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT 'DNI',
  `nro_doc` varchar(32) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `fecha_nac` date DEFAULT NULL COMMENT 'Fecha de nacimiento',
  `tel_movil` varchar(50) DEFAULT NULL,
  `dir` json DEFAULT NULL,
  `cpa` varchar(10) DEFAULT NULL,
  `ciudad_id` int DEFAULT '0',
  `ciudad_nombre` varchar(100) DEFAULT NULL,
  `region_id` int DEFAULT '0',
  `region_nombre` varchar(100) DEFAULT NULL,
  `pais_id` int DEFAULT NULL,
  `pais_nombre` varchar(100) DEFAULT 'Argentina',
  `data` json DEFAULT NULL,
  `sys_fecha_alta` datetime DEFAULT NULL COMMENT 'Fecha de alta del registro',
  `sys_fecha_modif` datetime DEFAULT NULL COMMENT 'Fecha de la última modificación',
  `sys_usuario_id` int DEFAULT NULL COMMENT 'ID del usuario que genero el registro',
  PRIMARY KEY (`id`),
  KEY `nro_doc` (`nro_doc`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;